### ISSUE TITLE
Misscalculation of faithfulness and consistency

### ISSUE THREAD

**Issue by joaoassisnabais** [ai-systems/Task-2-SemEval-2024#1]
After inspecting the code after the latest commit main() on evaluate.py did not run, I believe I found some problems. Currently, the consistency calculation is defined as follows:

```
def consistency(predictions_preserving, predictions, gold):
    uuid_list = list(predictions_preserving.keys())
    N = len(uuid_list)
    results = []
    for key in uuid_list:
        if predictions_preserving[key]["Prediction"] == predictions[data[key]["Causal_type"][1]]["Prediction"]:
            results.append(1)
        else:
            results.append(0)
    Consistency = sum(results) / N
    return Consistency
```
There's no parameter named data and I suppose that what you meant to do was the following:

`if predictions_preserving[key]["Prediction"] == predictions[gold[key]["Causal_type"][1]]["Prediction"]:`

This way you get the key from the gold dictionary and look up the label in the model prediction. In the faithfulness calculation, there's a different problem. It's being calculated with the gold label and not the model prediction, however, it was defined by you in the [NLI4CT Evaluation section](https://sites.google.com/view/nli4ct/semeval-2024/evaluation?authuser=0) as

$$\text{Faithfulness} = \frac{1}{N} \sum_{i=1}^{N} |f(y_i) - f(x_i)|$$,

which is not happening given that it's currently defined as:
```
def faithfulness(predictions, gold):
    uuid_list = list(predictions.keys())
    N = len(uuid_list)
    results = []
    for key in uuid_list:
        if predictions[key]["Prediction"] != gold[gold[key]["Causal_type"][1]]["Label"]:
            results.append(1)
        else:
            results.append(0)
    Faithfulness = sum(results) / N
    return Faithfulness
```
This way it's implementing 

$$\text{Faithfulness} = \frac{1}{N} \sum_{i=1}^{N} |g(y_i) - f(x_i)|$$, 
where $$g()$$ is the gold label for $$y_i$$. 

I believe the correct implementation would be:

```
def faithfulness(predictions_altering, predictions, gold):
    uuid_list = list(predictions.keys())
    N = len(uuid_list)
    results = []
    for key in uuid_list:
        if predictions_altering[key]["Prediction"] != predictions[gold[key]["Causal_type"][1]]["Prediction"]:
            results.append(1)
        else:
            results.append(0)
    Faithfulness = sum(results) / N
    return Faithfulness
```

Any response to clarify this matter would be greatly appreciated. Many thanks for considering my request.

**Comment by Mael7307** [comment]
Hello,

Thank you for identifying the issue with the consistency function—it’s now been corrected!

Regarding faithfulness, I realize our explanation may have been unclear. As shown in the equation, we define `f(y)` as `Label(y)`, the gold label, rather than as the model’s prediction on  `y`. This is intentional because faithfulness is designed to measure the extent to which a system arrives at the correct prediction for the correct reason.
![Screenshot 2024-11-13 at 12 11 29](https://github.com/user-attachments/assets/5927b32f-daf5-4a95-8bef-fbbd7664035b)
If we were to compare the predicted label of the intervened statement with the prediction on the original statement (disregarding correctness), we’d be measuring the model’s sensitivity to semantic changes alone. However, our goal with faithfulness is not only to verify that the model detects the intervention but to ensure it accurately interprets the meaning change in line with the correct label.

Thank you again for your feedback, and lets us know if you have more questions.

**Comment by joaoassisnabais** [comment]
Hello,

Thank you for the explanation in regard to the faithfulness calculation. Glad to help.

**Comment by joaoassisnabais** [comment]
Hello,

Thank you for the explanation in regard to the faithfulness calculation. Glad to help.
